### ISSUE TITLE
Add docker-compose file to the documentation

### ISSUE THREAD

**Issue by ItsNoted** [zusam/zusam#53]
Are you still actively maintaining this project? Asking for a friend. Thank you!

**Comment by nrobinaubertin** [comment]
I will continue development of the project. But life got in the way since last release and since I'm alone, it'll have to wait for now.  
If someone wants to help maintain and develop the project, PRs are welcome, I will read/approve them.

**Comment by ItsNoted** [comment]
I hope you are well and things are ok!

I was just curious if you could maybe simplify the install process with a docker compose file?

**Comment by mariushosting** [comment]
> I hope you are well and things are ok!
> 
> I was just curious if you could maybe simplify the install process with a docker compose file?

```
version: '3.9'
services:
    zusam:
        container_name: zusam
        ports:
            - 5560:8080
        volumes:
            - yourpathfolder:/zusam/data
        environment:
            - INIT_USER=user
            - INIT_PASSWORD=password
        restart: always
        image: zusam/zusam:0.5.1
```

Hope this helps.
